import React,  { useState } from 'react';

const IdeaComponent = () => {
  const [selectedInfo, setSelectedInfo] = useState(null);

  const handleInfoClick = (info) => {
    setSelectedInfo(info);
  };
  
  return (
      <div className="idea-container">
         <h2>Ideen zur Nutzung des Tools und Analyseaufgaben</h2>
        <div className="IdeasContainer">
        <p><strong>Aufgaben mit Beispielen:</strong></p>
        <p>Benutze die Beispiele mithilfe der Buttons oben links und mache dich mit der Benutzung und Funktion der Blöcke vertraut. Bevor du dir den Code ausgeben lässt, versuche zu verstehen, wie die Blöcke arbeiten. Klicke auf die Aufgaben, um die einzelen Aufgabenstellungen zu lesen.</p>
          <ul className="Examples">
          <li onClick={() => handleInfoClick('Lade das <strong>1. Beispiel</strong> und schaue dir die Blöcke an. Stelle eine mögliche <strong>Hypothese</strong> auf, die mithilfe der vorliegenden Blöcke untersucht wird. <br><br> Führe den Code der Blöcke aus. Kannst du dir deine <strong>Hypothese</strong> mit den Ergebnissen auch beantworten?')} className="clickable-item">Aufgabe 1</li>
          <li onClick={() => handleInfoClick('Lade das <strong>2. Beispiel</strong> und stelle deine Daten mithilfe eines <strong>Scatterplots</strong> dar, indem du den Code der Beispielblöcke ausführst. Was genau zeigt er an und wie würdest du ihn interpretieren?')} className="clickable-item">Aufgabe 2</li>
          <li onClick={() => handleInfoClick('Lade das <strong>3. Beispiel</strong> und finde mit dem Code der Blöcke heraus, was zuletzt die <strong>größte durchschnittliche Geschwindigkeit in km/h der drei verwendeten Boxen</strong> war. <br><br> Wie kommt das Tool auf das Ergebnis und was müsstest du verändern, um die <strong>langsamste Geschwindigkeit</strong> zu finden?')} className="clickable-item">Aufgabe 3</li>
          </ul>
        <p>Die Beispiele zeigen, dass das Tool die Blöcke nach einem einfachen Schema verwendet. Wenn es darum geht, Sensorwerte zu beschaffen und damit weiterzuarbeiten, wird zuerst ein Block für eine Sensoranfrage verwendet, in den der Block für die Sensebox mit einer bestimmten Nummer eingefügt wird. Anschließend werden die Sensordaten unter einem Variablennamen mithilfe des Textblocks gespeichert. Nun kann man den Variablennamen verwenden, um die zuvor gewonnenen Daten in weitere Blöcke einzufügen und sie zu analysieren und zu visualisieren. Nutze dieses Wissen über das Vorgehen für die Bearbeitung der freien Aufgaben.</p> 
        <p><strong>Weitere Aufgaben:</strong></p>
        <p>Versuche nun die freien Aufgaben zu lösen. Klicke auf die Aufgabe, um die Aufgabenstellung zu lesen und nutze die Hilfen im Wiki oder in der Blockbeschreibung, falls du nicht weiterkommst.</p>
          <ul className="Beginner">
          <li onClick={() => handleInfoClick('Wo befindet sich <strong>Box #29</strong> aktuell? Benutze dafür die Blöcke und suche sie anschließend auf der <strong>Karte</strong>.')} className="clickable-item">Aufgabe 4</li>
          <li onClick={() => handleInfoClick('Hole dir die <strong>Sensorwerte einer Box deiner Wahl</strong>, für die du dich interessierst. <br><br> Speichere sie in einer Variable ab und lasse dir eine <strong>Zusammenfassung über deine Stichprobe</strong> ausgeben. <br><br> Was sagen die einzelnen Werte aus? Warum ist der <strong>Median</strong> unterschiedlich vom <strong>Mittelwert</strong> und kannst du das <strong>Streuungsmaß mit den Quantilen</strong> bestimmen? <br><br> (Tipp: Eine Zusammenfassung einer Stichprobe zu erstellen, ist Bestandteil der Datenanalyse und kann mit einem einzigen Block gemacht werden.)')} className="clickable-item">Aufgabe 5</li>
          <li onClick={() => handleInfoClick('Sieh dir den <strong>Boxplot der Feinstaubmessungen PM10 von Sensebox #6</strong> auf der About-Seite an und beschreibe und deute die Darstellung.<br><br>  Nutze die Informationen über Visualisierungsformen im Wiki.')} className="clickable-item">Aufgabe 6</li>
          <li onClick={() => handleInfoClick('Die Temperatur im Juli 2022 betrug in Deutschland durchschnittlich 19,2°C. Hole dir die <strong>Temperaturwerte der SenseBox #6</strong> und führe einen <strong>gerichteten Einstichproben-t-Test</strong> mit den SenseBox Daten als dein Sample durch.<br><br> Deine zu untersuchende Hypothese lautet: <strong>Die Temperaturen im Juli 2023 gemessen durch Sensebox #6 sind signifikant größer sind als der Bundesdurchschnitt im letzten Jahr</strong>. <br><br> Deine H0 lautet also: <strong>Die Temperaturen im Juli 2023 gemessen durch Sensebox #6 sind gleich groß wie der Bundesdurchschnitt im letzten Jahr</strong>.<br><br> Kannst du die H0 ablehnen? Der Name deiner Variable muss wie immer als Text und der Mittelwert als Zahl gespeichert werden. Infos über die auszuwählende Richtung für den t-Test gibt dir die zu untersuchende Hypothese in der Aufgabenstellung.')} className="clickable-item">Aufgabe 7</li>
          </ul>
        <p><strong>Lösungsansätze:</strong></p>
        <p>Schaue dir die Musterlösungen zu den einzelnen Aufgaben an, um deine Ergebnisse zu vergleichen. </p>
        <ul className="Examples">
        <li onClick={() => handleInfoClick('Das 1. Beispiel lädt Blöcke ein, die die letzten gemessenen <strong>Temperaturwerte von SenseBox #3 und SenseBox #10 in jeweils den Variablen tempBox3 und tempBox10 speichern</strong>.<br><br> Anschließend wird für jede Stichprobe der <strong>Mittelwert</strong> berechnet und eine <strong>Vergleichsoperation</strong> - in diesem Fall > (größer als) - durchgeführt. <br><br> Die Wahl der Blöcke zielt darauf ab, herauszufinden, welche Box im Durchschnitt höhere Temperaturen gemessen hat. Die These dazu könnte also lauten: <strong>SenseBox #3 hat in letzter Zeit höhere Werte für den Temperatursensor erhalten, als SenseBox #6</strong>. Da du als Ergebnis <strong>TRUE</strong> erhälst, kannst du diese Annahme nun auch bestätigen. ')} className="clickable-item">Lösung Aufgabe 1</li>
        <li onClick={() => handleInfoClick('Das 2. Beispiel beschafft die letzten <strong>Temperatur- und Luftfeuchtigkeitsmessungen der SenseBox #6</strong>. Anschließend wird ein <strong>Scatterplot mit der Temperatur auf der x-Achse und der Luftfeuchtigkeit auf der y-Achse</strong> erstellt und eine Regressionslinie eingezeichnet, falls eine Beziehung zwischen den beiden Variablen besteht.<br><br> Dein Plot zeigt eine <strong>zufällige Anordnung</strong> der Wertepaare aus Temperatur und Luftfeuchtigkeit. Das deutet darauf hin, dass die Werte nicht miteinander korrelieren. Man kann also beispielsweise nicht erkennen, dass ein erhöhter Temperaturwert ein Ansteigen oder Fallen der Luftfeuchtigkeit verursachen würde. ')} className="clickable-item">Lösung Aufgabe 2</li>
        <li onClick={() => handleInfoClick('Das 3. Beispiel beinhaltet Anfragen an die <strong>Geschwindigkeitsmessungen von 3 Boxen</strong>. Diese werden in die <strong>Variablen speebBox3, speedBox5 und speedBox23</strong> gespeichert. <br><br> Der letzte verschachtelte Teil <strong>füllt eine Liste mit den Mittelwerten dieser Geschwindigkeitsmessungen</strong>, die Liste beinhaltet also genau 3 Werte. <br><br> Der Block, der diese Liste umschließt berechnet den größten Wert diese Liste. Das ist also nichts anderes als die <strong>durchschnittliche Geschwindigkeit der schnellsten Box</strong>. <br><br> Man kann den Block so verändern, dass er den kleinsten Wert aus der Liste suchen würde. Dazu muss einfach <strong>"maximum von" in "minimum von"</strong> getauscht werden und der Code findet nun die langsamste Box. ')} className="clickable-item">Lösung Aufgabe 3</li>
        <li onClick={() => handleInfoClick('Um den <strong>Standort einer Box</strong> zu bestimmen, nutze den <strong>"Aktuelle Koordinaten"-Block</strong> aus der Senseboxen-Kategorie und verknüpfe ihn mit <strong>SenseBox #29</strong>. Dein Ergebnis enthält zwei Werte im Dezimalgrad, lat und lon. Der <strong>lat-Wert</strong> gibt an, auf welchem Breitengrad sich deine Box befindet und der <strong>lon-Wert</strong> beschreibt die Position auf dem Längengrad der Erde.<br><br> Die Karte findest du unter dem Reiter "Map" gleich neben dem Wiki. Die Marker repräsentieren die Standorte jeder Box und sind mit einem kleinen Textfeld ausgestattet. Wenn du sie anklickst, findest du heraus, welcher Marker zu welcher SenseBox gehört.  ')} className="clickable-item">Lösung Aufgabe 4</li>
        <li onClick={() => handleInfoClick('Um die Werte eines Sensors einer Box zu erfahren, <strong>wähle einen Block aus der Kategorie "Sensor-Anfragen" und kombiniere ihn mit einer Box aus der Kategorie "Senseboxen"</strong>. Bei dieser Aufgabe kannst du die Art des Sensors und die SenseBox Nummer frei wählen. <br><br>Um die Daten in einer Variable zu speichern, suche unter "Operationen" nach dem Block, der einen <strong>Sensorwert aus der Dropdown-Liste unter einem Namen speichert, den du ihm mit dem Textfeld aus "Listen und Text" gibst</strong>. <br><br>Eine Zusammenfassung über eine Stichprobe erstellt R mit der summary() Funktion, die in dem Block mit dem Titel "<strong>Zusammenfassung</strong>" unter "Datenanalyse" zu finden ist. <br><br>Du erhälst jetzt Informationen über den <strong>kleinsten und größten Wert</strong> deiner Stichprobe, das <strong>1. und 3. Quartil</strong> sowie den <strong>Mittelwert</strong> und den <strong>Median</strong>. Der Median stellt hier den Wert dar, bei dem 50% der Werte einen höheren Wert haben, der Mittelwert ist hingegen der Durchschnitt aller Werte. Um den Median zu bestimmen, kannst du deine Daten sortieren und die Mitte wählen, falls du eine ungerade Anzahl an Werten hast. Um den Mittelwert zu berechnen, musst du alle Werte addieren und durch die Anzahl der Werte teilen. Das Streuungsmaß kann mithilfe der Quartile berechnet werden, indem du den Wert des 1. Quartils vom Wert des 3. Quartils abziehst und die Differenz betrachtest, also die Hälfte aller Werte, die sich um den Median befinden. ')} className="clickable-item">Lösung Aufgabe 5</li>
        <li onClick={() => handleInfoClick('Um Aufgabe 6 zu lösen, benötigst du im Moment keine weiteren Blöcke. Wenn du dir die Informationen im Wiki durchgelesen hast, weißt du, dass der <strong>Boxplot auf der About Seite</strong> aus verschiedenen Bestandteilen besteht, die dir unterschiedliche Informationen über die Stichprobe verraten. <br><br>Die Beschriftung der x-Achse und y-Achse geben an, dass es sich um einen Boxplot des <strong>Feinstaubs PM10</strong> handelt und sich die Werte der Variable etwa zwischen 2.5 und 5.5 μg/m³ befinden. Die namensgebende Box zeigt dir das <strong>1. und 3. Quartil</strong> sowie den <strong>Median</strong> als Linie eingezeichnet. Der Median befindet sich also etwa bei 3.3. Die <strong>Whisker</strong> des Plots geben den kleinsten und größten Wert der Stichprobe an, hier also etwa 2.6 und 4.6. Die Stichprobe scheint auch einen <strong>Ausreißer</strong> zu beinhalten bei etwa 5.4, der durch den Kreis am oberen Ende des Plots dargestellt wird. Du kannst deine Einschätzungen der Werte überprüfen, indem du dir die Zusammenfassung der PM10 Messung von SenseBox #6 mithilfe der Blöcke ausgeben lässt (s. Aufgabe 4). ')} className="clickable-item">Lösung Aufgabe 6</li>
        <li onClick={() => handleInfoClick('Um den <strong>t-Test</strong> durchführen zu können, musst du dir dein Sample beschaffen, indem du unter "Sensor-Anfragen" den Block für die <strong>Temperaturmessungen</strong> auswählst und diesen mit <strong>SenseBox #6</strong> kombinierst.<br><br> <strong>Speichere die Daten in einer Variable</strong> mit Namen deiner Wahl und wähle in der Liste des Blocks "Temperatur" aus, damit die passenden Werte gespeichert werden. <br><br>Nun musst du den Block für den <strong>Einstichproben-t-Test</strong> verwenden und kannst das Sample und den Mittelwert der Grundgesamtheit eintragen. Dein Sample ist unter dem Variablennamen gespeichert. <br><br> Der Mittelwert ist aus der Aufgabenstellung bekannt und du kannst ihn mit einem einfachen Block für eine Zahleneingabe aus der Kategorie "Mathematik" dort eintragen.<br><br> Die für die Interpretation deines Ergebnisses entscheidenden Werte sind die des t-Werts und des p-Werts. Der <strong>p-Wert ist mit 7.869e-16 sehr nah an 0 </strong>(0,0000000000000007869), was darauf hindeutet, dass es <strong>sehr unwahrscheinlich ist, dass die Nullhypothese wahr ist</strong>. Zudem lässt die Tatsache <strong>dass der p-Wert positiv ist (30.164) darauf schließen, dass der Mittelwert des Samples höher ist, als der gegebene</strong>.  Wir können die H0 also verwerfen und darauf schießen, dass es einen <strong>signifikanten Unterschied zwischen dem sample-Mittelwert (20,74) und dem Mittelwert der Grundgesamtheit gibt (19,2).</strong> ')} className="clickable-item">Lösung Aufgabe 7</li>
        </ul>

          {selectedInfo && (
        <div className="info-popup-container">
          <div className="info-popup">
            <button className="close-button" onClick={() => setSelectedInfo(null)}>Zurück</button>
            <p dangerouslySetInnerHTML={{ __html: selectedInfo }}></p>
          </div>
        </div>
      )}
        </div>
      </div>
    
  );
};

export default IdeaComponent;
